/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataViewLayoutOptions: typeof import('primevue/dataviewlayoutoptions')['default']
    Divider: typeof import('primevue/divider')['default']
    DocsTableSkeleton: typeof import('./src/components/DocsTableSkeleton.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeaderTemplate: typeof import('./src/components/HeaderTemplate.vue')['default']
    Image: typeof import('primevue/image')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskCardSkeleton: typeof import('./src/components/TaskCardSkeleton.vue')['default']
    TaskGrid: typeof import('./src/components/TaskGrid.vue')['default']
    TempCodeRunnerFile: typeof import('./src/components/tempCodeRunnerFile.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
